### ISSUE TITLE
PWM

### ISSUE THREAD

**Issue by Madhurjot** [EduardoNigro/labjack-unified#1]
The PWM code has some bugs. I have been trying to get PWM set on FIO0, however, I get errors regarding missing attributes from the source files. I tried running the sample code from the website which also failed. I have attached some screenshots as well. Please take a look at this issue. Thanks
<img width="224" alt="PWM Error 2" src="https://user-images.githubusercontent.com/48146018/226784166-93d6f148-8745-4674-8a15-daaa4f4cdb64.png">
<img width="463" alt="PWM Error" src="https://user-images.githubusercontent.com/48146018/226784170-352d6eab-0431-49e1-a535-f906807db8ea.png">

**Comment by EduardoNigro** [comment]
Hello,

That's odd. The `_corefreq` attribute is defined as soon as the T7 object is created.
Try the following statements:

```python
# Importing T7 class
from labjack_unified.devices import LabJackT7
# Creating T7 object
lj = LabJackT7()
# Checking for attribute
print(lj._corefreq)
```
You should get a value of 80,000,000 i.e. 80 MHz

Also, I am assuming you do have an actual LabJack T7 connected to your Windows PC via USB cable.

Let me know what you get.
Regards,
Eduardo
